CREATE DATABASE PortGalati
GO
USE PortGalati;

CREATE TABLE Porturi(
	idP INT NOT NULL PRIMARY KEY IDENTITY,
	TipPort NVARCHAR(25) DEFAULT 'Mediu',
	Tara NVARCHAR(60),
	NrNave INT NOT NULL,
	Plecari DATETIME,
	Sosiri DATETIME
);

CREATE TABLE Depozite(
	idD INT NOT NULL PRIMARY KEY IDENTITY,
	
);

CREATE TABLE Manageri(
	idMg INT NOT NULL PRIMARY KEY IDENTITY,
	NumeMg NVARCHAR(100) DEFAULT 'Anon',
	Varsta INT CHECK (Varsta >= 18 AND Varsta <= 65)
);

CREATE TABLE Angajati(
	idAgj INT NOT NULL PRIMARY KEY IDENTITY,
	NumeAgj NVARCHAR(100) DEFAULT 'Anon',
	VarstaAgj INT CHECK (VarstaAgj >= 18 AND VarstaAgj <= 65),
	idMg INT NOT NULL FOREIGN KEY REFERENCES Manageri(idMg)
);


CREATE TABLE Marfuri(
	idM INT NOT NULL PRIMARY KEY IDENTITY,
	Origine NVARCHAR(60) DEFAULT 'Global',
	Tonaj FLOAT NOT NULL,

);

CREATE TABLE Companii(
	idC INT NOT NULL PRIMARY KEY IDENTITY,
	NumeCompanie NVARCHAR(100),
	Tara NVARCHAR(60),
	TipCompanie NVARCHAR(25),
    
);

